In [255]:
# Phase A: Load and understand the data
import numpy as np
import pandas as pd
import sqlite3

df = pd.read_csv('timesData.csv')
print(df.shape)
print(df.dtypes)
df.head(10)
df.describe()
df.tail(5)
df.isnull().sum()
print(df.tail())

(2603, 14)
world_rank                 object
university_name            object
country                    object
teaching                  float64
international              object
research                  float64
citations                 float64
income                     object
total_score                object
num_students               object
student_staff_ratio       float64
international_students     object
female_male_ratio          object
year                        int64
dtype: object
     world_rank               university_name      country  teaching  \
2598    601-800           Yeungnam University  South Korea      18.6
2599    601-800   Yıldız Technical University       Turkey      14.5
2600    601-800      Yokohama City University        Japan      24.0
2601    601-800  Yokohama National University        Japan      20.1
2602    601-800            Yuan Ze University       Taiwan      16.2

     international  research  citations income total_score num_students  \
2598          24.3      10.9       26.5   35.4           -       21,958
2599          14.9       7.6       19.3   44.0           -       31,268
2600          16.1      10.2       36.4   37.9           -        4,122
2601          23.3      16.0       13.5   40.4           -       10,117
2602          17.7      18.3       28.6   39.8           -        8,663

      student_staff_ratio international_students female_male_ratio  year
2598                 15.3                     3%           48 : 52  2016
2599                 28.7                     2%           36 : 64  2016
2600                  3.7                     3%               NaN  2016
2601                 12.1                     8%           28 : 72  2016
2602                 20.6                     4%           43 : 57  2016

# Data Overview
* 2603 rows (schools) and 14 columns (metrics)
* university_name, country are identifiers
* columns num_students, student_stuff_ratio, international_students are each missing about 2% of the data, and column female_male_ratio misses about 10% of the dataset

In [239]:
df.describe()
df.tail(4)
df['country'].value_counts()[:15]
df['year'].value_counts()
df['country'].value_counts() # 72 countries were represented, and the US leads with 659 results

country
United States of America     659
United Kingdom               300
Germany                      152
Australia                    117
Canada                       108
                            ...
Unted Kingdom                  1
Cyprus                         1
Unisted States of America      1
Luxembourg                     1
Lithuania                      1
Name: count, Length: 72, dtype: int64

# Descriptive statistics — initial observations
 
* The US dominates by the number of appearance. The data covers 6 years from 2011 to 2016.

* The max values for all metrics seem fine; for the min values, a minimum `student_staff_ratio` near 0.6 is implausibly low and is probably data input error. Besides, `teaching` and `research` both have very low minimum values, suggesting either 
  outlier institutions or additional sentinel values not yet cleaned

In [225]:
# Phase B: Clean the data
print(df[['teaching','research','citations','income','international','total_score']].dtypes) 
df['international'].unique()

teaching         float64
research         float64
citations        float64
income            object
international     object
total_score       object
dtype: object

array(['72.4', '54.6', '82.3', '29.5', '70.3', '77.7', '77.2', '39.6',
       '90.0', '59.2', '48.1', '62.8', '58.5', '62.4', '93.7', '53.3',
       '-', '90.9', '32.9', '39.1', '91.4', '90.8', '49.0', '49.4',
       '60.5', '18.4', '73.2', '32.6', '64.3', '93.3', '21.5', '31.6',
       '55.9', '97.8', '85.9', '88.0', '68.6', '56.4', '77.9', '67.3',
       '97.4', '44.9', '93.9', '44.5', '43.7', '31.2', '100.0', '66.3',
       '22.1', '23.0', '28.3', '22.6', '43.0', '38.1', '31.8', '52.3',
       '43.1', '35.6', '25.2', '56.5', '64.0', '31.7', '67.2', '16.7',
       '89.6', '42.2', '87.5', '20.9', '84.2', '52.2', '36.7', '72.8',
       '74.2', '66.6', '63.4', '22.5', '65.7', '99.5', '79.1', '92.9',
       '56.8', '69.0', '87.9', '24.4', '87.0', '21.9', '91.3', '35.4',
       '31.0', '37.6', '85.3', '24.2', '85.7', '48.0', '26.8', '62.6',
       '34.1', '83.3', '19.9', '71.8', '47.7', '24.8', '29.2', '34.2',
       '63.0', '95.7', '29.6', '50.2', '91.0', '30.4', '24.7', '73.8',
       '40.0', '71.6', '55.1', '20.1', '46.2', '84.1', '62.7', '30.6',
       '30.7', '54.4', '22.3', '52.6', '24.3', '94.3', '19.3', '82.9',
       '86.1', '47.4', '88.5', '80.5', '70.7', '44.1', '37.7', '23.2',
       '16.3', '58.6', '16.8', '24.1', '21.3', '38.2', '59.8', '33.4',
       '50.0', '40.3', '35.5', '29.3', '56.1', '96.3', '74.8', '45.8',
       '46.1', '87.1', '46.8', '57.9', '63.8', '27.2', '93.6', '47.3',
       '57.8', '60.6', '18.9', '28.0', '64.2', '63.2', '15.9', '51.8',
       '51.9', '56.0', '67.5', '57.2', '91.9', '49.6', '79.2', '92.2',
       '58.8', '50.4', '55.5', '67.6', '41.0', '59.9', '97.5', '34.3',
       '91.8', '47.2', '53.4', '55.0', '46.9', '88.7', '65.0', '36.9',
       '35.3', '23.8', '81.4', '38.8', '50.7', '82.0', '31.5', '83.7',
       '79.8', '82.5', '93.8', '51.4', '93.0', '45.7', '25.6', '20.2',
       '54.3', '98.9', '96.0', '80.4', '51.7', '21.1', '25.0', '37.2',
       '41.1', '88.1', '26.5', '66.2', '87.4', '80.1', '27.3', '72.0',
       '73.7', '56.7', '58.1', '39.7', '62.3', '80.8', '37.3', '75.9',
       '41.3', '30.8', '61.2', '25.3', '75.8', '66.7', '89.1', '36.3',
       '59.1', '65.2', '33.1', '29.9', '34.0', '28.4', '71.9', '68.2',
       '68.1', '73.9', '71.3', '79.5', '24.9', '64.5', '29.8', '92.4',
       '77.6', '23.3', '86.7', '89.4', '53.0', '72.7', '69.3', '25.9',
       '26.1', '88.8', '78.3', '78.6', '48.8', '64.8', '38.3', '26.4',
       '29.1', '86.6', '72.6', '30.0', '32.7', '68.5', '76.2', '19.7',
       '69.5', '62.1', '84.8', '20.7', '73.4', '85.5', '83.2', '23.9',
       '17.2', '36.0', '75.1', '30.1', '67.1', '89.8', '72.5', '30.3',
       '85.1', '62.5', '70.5', '22.9', '57.6', '73.1', '63.9', '82.1',
       '55.6', '73.5', '14.8', '61.6', '63.7', '41.4', '64.9', '32.1',
       '86.4', '84.9', '56.2', '45.9', '48.5', '67.8', '38.4', '21.2',
       '17.7', '38.0', '48.9', '50.8', '52.0', '49.2', '81.7', '20.6',
       '90.1', '48.4', '90.7', '26.0', '70.4', '55.7', '44.0', '66.0',
       '25.5', '37.8', '36.1', '23.4', '43.5', '17.8', '34.9', '42.7',
       '56.3', '33.2', '26.9', '45.5', '45.2', '89.9', '56.6', '19.5',
       '16.0', '57.7', '89.5', '46.6', '44.4', '69.1', '80.6', '34.6',
       '35.9', '71.7', '89.0', '25.1', '24.6', '18.8', '58.9', '23.5',
       '52.9', '76.7', '19.1', '71.0', '18.0', '63.5', '42.6', '33.3',
       '56.9', '18.3', '43.3', '76.3', '49.7', '75.3', '47.0', '36.2',
       '46.7', '14.3', '39.5', '48.6', '15.6', '33.6', '32.4', '20.5',
       '12.7', '26.6', '77.0', '33.5', '37.1', '76.5', '27.7', '68.7',
       '40.2', '18.6', '26.2', '42.0', '15.0', '81.5', '36.4', '35.8',
       '13.9', '84.5', '28.5', '27.9', '79.0', '21.0', '82.6', '23.6',
       '18.1', '31.4', '45.0', '77.8', '32.3', '22.2', '48.3', '63.3',
       '64.6', '30.5', '55.8', '27.4', '81.8', '21.8', '28.8', '27.1',
       '21.7', '12.8', '81.6', '54.5', '83.6', '55.3', '54.7', '42.3',
       '66.1', '57.3', '53.8', '33.8', '47.6', '65.1', '42.1', '27.6',
       '92.3', '78.9', '58.3', '87.2', '98.8', '38.7', '44.3', '54.1',
       '28.7', '46.3', '39.2', '26.3', '43.4', '86.0', '27.0', '83.0',
       '54.8', '78.1', '31.1', '51.0', '59.0', '29.4', '67.7', '61.3',
       '36.6', '64.4', '57.0', '74.6', '90.5', '66.9', '49.8', '34.7',
       '49.1', '36.8', '41.6', '35.2', '40.4', '31.3', '57.5', '66.4',
       '61.5', '27.5', '86.3', '69.8', '85.2', '92.5', '70.1', '32.5',
       '80.9', '60.9', '82.7', '77.4', '95.3', '50.3', '32.0', '69.7',
       '47.1', '54.9', '52.4', '77.3', '74.1', '53.9', '24.5', '52.8',
       '66.8', '61.0', '54.0', '82.2', '68.9', '74.4', '51.2', '25.8',
       '88.4', '19.0', '65.9', '45.3', '38.6', '49.9', '58.0', '30.9',
       '46.0', '22.0', '68.3', '65.3', '58.4', '16.1', '62.2', '85.4',
       '51.3', '44.8', '78.2', '65.4', '86.8', '69.2', '47.8', '19.6',
       '40.5', '44.6', '35.7', '43.2', '30.2', '71.4', '63.1', '47.5',
       '20.8', '54.2', '28.1', '27.8', '62.0', '61.8', '71.5', '59.5',
       '59.7', '39.0', '37.0', '34.4', '70.2', '81.0', '35.0', '85.6',
       '33.9', '68.4', '41.7', '48.2', '73.3', '48.7', '42.4', '74.7',
       '28.6', '40.8', '39.8', '32.8', '65.8', '90.2', '68.0', '59.6',
       '46.4', '96.7', '59.3', '40.6', '49.5', '70.0', '81.3', '98.2',
       '41.8', '80.3', '33.7', '44.2', '53.7', '79.7', '51.5', '91.1',
       '75.0', '76.8', '58.7', '65.5', '73.6', '92.6', '75.6', '83.5',
       '86.2', '67.4', '39.4', '81.2', '76.0', '72.2', '61.9', '57.1',
       '78.5', '43.6', '79.6', '50.6', '61.1', '88.6', '72.3', '55.4',
       '77.5', '67.0', '23.7', '70.6', '37.9', '62.9', '29.0', '25.4',
       '42.8', '45.1', '69.4', '28.9', '82.4', '67.9', '40.7', '38.5',
       '83.9', '70.8', '68.8', '87.8', '71.2', '22.8', '50.1', '81.1',
       '38.9', '37.4', '80.0', '87.3', '28.2', '53.2', '42.9', '15.3',
       '17.3', '14.7', '74.3', '34.5', '21.6', '50.9', '22.4', '26.7',
       '43.9', '69.9', '39.3', '29.7', '84.3', '92.7', '96.6', '43.8',
       '50.5', '90.6', '94.9', '47.9', '41.2', '46.5', '81.9', '94.5',
       '78.7', '76.6', '91.2', '51.1', '32.2', '78.8', '89.7', '64.7',
       '86.9', '96.8', '94.4', '84.0', '84.7', '80.7', '44.7', '79.3',
       '60.1', '60.3', '60.4', '39.9', '93.4', '79.4', '84.4', '61.4',
       '59.4', '18.2', '41.5', '89.2', '37.5', '19.4', '76.1', '88.2',
       '52.1', '34.8', '45.6', '66.5', '16.6', '20.0', '53.6', '60.0',
       '74.9', '21.4', '91.5', '97.9', '96.2', '49.3', '98.6', '33.0',
       '94.6', '89.3', '87.6', '85.8', '58.2', '90.3', '95.5', '63.6',
       '52.7', '93.5', '94.7', '92.8', '90.4', '80.2', '98.5', '88.3',
       '53.1', '31.9', '99.8', '65.6', '60.2', '40.1', '45.4', '16.4',
       '53.5', '76.9', '97.6', '78.0', '72.9', '17.1', '75.5', '25.7',
       '93.1', '15.5', '13.3', '12.2', '98.4', '35.1', '15.8', '36.5',
       '41.9', '23.1', '7.7', '17.6', '12.9', '22.7', '17.4', '14.1',
       '17.5', '95.0', '17.9', '18.7', '95.6', '7.2', '16.9', '13.7',
       '13.1', '15.7', '20.4', '19.8', '69.6', '15.4', '13.4', '14.5',
       '18.5', '55.2', '20.3', '7.1', '17.0', '14.2', '15.2', '99.9',
       '13.8', '14.0', '16.5', '14.9'], dtype=object)

In [226]:
score_cols = ['teaching', 'international', 'research', 'citations', 'income','total_score']
for score in score_cols:
    df[score]= pd.to_numeric(df[score],errors='coerce') 
    print(df[score].dtype)

print (df.isnull().sum())  # null counts increase as '-' sentinels are coerced to NaN

float64
float64
float64
float64
float64
float64
world_rank                   0
university_name              0
country                      0
teaching                     0
international                9
research                     0
citations                    0
income                     218
total_score               1402
num_students                59
student_staff_ratio         59
international_students      67
female_male_ratio          233
year                         0
dtype: int64

In [241]:
df['rank_numeric'] = df['world_rank'].str.extract(r'(\d+)')
df['rank_numeric'] = pd.to_numeric(df['rank_numeric'], errors='coerce')

df['country'] = df['country'].str.strip() 

df['is_top100'] = (df['rank_numeric'] <= 100).astype(int) # cast bool to int: True to 1, False to 0

In [228]:
# Create a Python dictionary that maps country names to regions. 

df['country'].value_counts()[:10]
region_dic = {'United States of America': 'North America','United Kingdom': 'Europe', 'Germany':'Europe','Australia':'Oceania','Canada':'North America', 'Japan':'Asia',
              'Italy' :'Europe', 'China':'Asia', 'Netherlands':'Europe', 'France':'Europe'}
df['region'] = df['country'].map(region_dic).fillna('Other')
print(df.shape)
print(df.dtypes)

(2603, 17)
world_rank                 object
university_name            object
country                    object
teaching                  float64
international             float64
research                  float64
citations                 float64
income                    float64
total_score               float64
num_students               object
student_staff_ratio       float64
international_students     object
female_male_ratio          object
year                        int64
rank_numeric                int64
is_top100                   int64
region                     object
dtype: object

## Cleaning summary 
* we now have 3 extra columns added (`rank_numeric`, `is_top100`, `region`) for raw data of 2603 rows.
* During the cleaning, we strip off unnecessary spaces in the data and then convert the data types of scores from objects/strings to numerical values by replacing null values with NaNs. 
* `world_rank` ranges like '201–250' and prefixed values like '=5' were resolved to their leading integer and saved in `rank_numeric`.

In [229]:
# Phase C: Explore and aggregate
# aggregate by country: university count, average scores, best rank
country_stats = (
    df.groupby('country').agg(
        numb_of_U=('world_rank','count'),
        avg_total_score  = ('total_score', 'mean'),
        best_rank        = ('rank_numeric', 'min'),
        avg_teaching_score     = ('teaching', 'mean'),
        avg_research_score     = ('research', 'mean'),
        avg_citations_score    = ('citations', 'mean')).sort_values('avg_total_score', ascending=False))
print(country_stats.head(15))

#Part 2: Filter to only rows where is_top100 == 1, then group by country and count. 
# Sort descending: which country has the most top-100 universities?

print(df[df['is_top100'] == 1].groupby('country').size().sort_values(ascending = False))

                          numb_of_U  avg_total_score  best_rank  \
country
Singapore                        12        65.600000         25
United States of America        659        64.508009          1
China                            83        61.338889         37
Switzerland                      47        61.024390          9
Canada                          108        60.981250         17
Hong Kong                        34        60.213636         21
Australia                       117        60.120000         28
Japan                            98        59.474074         23
United Kingdom                  300        58.994086          2
South Korea                      57        58.821739         28
Sweden                           57        56.584375         28
Finland                          32        56.033333         76
Netherlands                      75        55.356522         47
France                           73        55.005556         39
Germany                         152        54.734177         29

                          avg_teaching_score  avg_research_score  \
country
Singapore                          56.500000           68.091667
United States of America           47.944310           45.152200
China                              38.789157           30.393976
Switzerland                        45.172340           44.395745
Canada                             39.007407           42.267593
Hong Kong                          42.582353           46.758824
Australia                          31.852137           36.118803
Japan                              40.838776           32.992857
United Kingdom                     37.170667           37.417333
South Korea                        42.217544           39.826316
Sweden                             35.715789           43.764912
Finland                            28.653125           27.378125
Netherlands                        40.970667           51.930667
France                             35.591781           26.345205
Germany                            39.303289           33.750658

                          avg_citations_score
country
Singapore                           65.341667
United States of America            74.811533
China                               41.980723
Switzerland                         77.206383
Canada                              60.687963
Hong Kong                           64.158824
Australia                           55.988889
Japan                               39.707143
United Kingdom                      66.715000
South Korea                         44.722807
Sweden                              63.747368
Finland                             56.478125
Netherlands                         66.576000
France                              69.178082
Germany                             66.437500
country
United States of America    281
United Kingdom               74
Netherlands                  33
Germany                      32
Australia                    31
Canada                       26
Switzerland                  18
France                       16
South Korea                  14
Sweden                       14
China                        13
Hong Kong                    12
Japan                        12
Singapore                    10
Belgium                       8
Finland                       3
Republic of Ireland           2
Denmark                       1
Italy                         1
Turkey                        1
dtype: int64

## Country-level observations
* The US has the most top-100 universities by count, but not the highest average total score. Luxembourg leads on average citations score. 
* The above distinction goes to countries with fewer but elite institutions. This reflects a volume vs. concentration distinction.

In [230]:
# average total score by region and year
pd.pivot_table(df, 
               values = 'total_score', 
               index = 'region', 
               columns = 'year',
               aggfunc='mean').round(1)

year           2011  2012  2013  2014  2015  2016
region
Asia           59.4  57.7  63.1  59.5  57.9  68.2
Europe         56.5  53.9  58.6  55.0  56.9  60.3
North America  65.7  63.1  65.4  61.6  62.5  67.2
Oceania        59.8  57.5  62.1  57.7  58.7  64.2
Other          56.1  53.0  57.7  53.7  55.2  58.1

## Regional score trends (2011–2016)

* Scores are broadly stable across years — no region shows a sustained upward or downward trend.

In [231]:
# citations impact vs. global rank
print(df[(df['citations']>90) & (df['rank_numeric']> 50)][['university_name', 'country','rank_numeric','citations']]) 

df[df['research'] > df['teaching']+ 20]
# research-teaching gap
df['research_lead'] = df['research'] - df['teaching']
print(df.sort_values(by = ['research_lead'], ascending= False)[:10])

print(df[df['university_name'].str.contains('MIT')][['total_score','rank_numeric']])

                                        university_name  \
58                                    Boston University
68                 University of California, Santa Cruz
72                               University of Adelaide
74                                       William & Mary
79                                 University of Sussex
...                                                 ...
2001                 Paris Diderot University – Paris 7
2030               Oregon Health and Science University
2034  Peter the Great St Petersburg Polytechnic Univ...
2052                             Wake Forest University
2069                              University of Iceland

                       country  rank_numeric  citations
58    United States of America            59       91.4
68    United States of America            68       99.6
72                   Australia            73       90.5
74    United States of America            75       95.6
79              United Kingdom            79       91.6
...                        ...           ...        ...
2001                    France           199       91.0
2030  United States of America           201       96.0
2034        Russian Federation           201       97.4
2052  United States of America           201       94.8
2069                   Iceland           251       91.4

[121 rows x 4 columns]
     world_rank                   university_name                   country  \
462     251-275                Tilburg University               Netherlands
1854         52    Australian National University                 Australia
1824         22        Carnegie Mellon University  United States of America
687          86  Nanyang Technological University                 Singapore
1830         28              Karolinska Institute                    Sweden
333         134           University of Groningen               Netherlands
673          72      Erasmus University Rotterdam               Netherlands
717         116                 Aarhus University                   Denmark
1867        =65    Delft University of Technology               Netherlands
728         127       Radboud University Nijmegen               Netherlands

      teaching  international  research  citations  income  total_score  \
462       22.6           69.1      49.4       23.6    36.0          NaN
1854      54.7           93.3      77.3       72.3    48.0         69.5
1824      67.4           57.1      88.8       99.1    57.5         82.3
687       45.7           90.5      66.9       54.5    99.5         59.4
1830      60.6           73.1      81.1       92.2    75.8         77.5
333       32.4           47.3      52.4       62.4    59.9         49.2
673       44.5           62.8      64.1       80.2    62.0         62.9
717       35.7           66.4      54.6       71.6    69.7         55.3
1867      55.0           84.0      73.8       61.5   100.0         65.9
728       35.7           53.4      54.3       73.3    41.7         54.0

     num_students  student_staff_ratio international_students  \
462         7,576                 22.4                    10%
1854       14,604                 19.2                    35%
1824       11,885                 13.1                    35%
687        25,028                 16.2                    33%
1830        7,774                 11.5                    22%
333        24,556                 25.6                    12%
673        20,580                 18.9                    18%
717        23,895                 13.6                    14%
1867       15,920                 19.4                    25%
728        17,713                 13.0                    10%

     female_male_ratio  year  rank_numeric  is_top100         region  \
462            49 : 51  2012           251          0         Europe
1854           52 : 48  2016            52          1        Oceania
1824           39 : 61  2016            22          1  North America
687            48 : 52  2013            86          1          Other
1830           70 : 30  2016            28          1          Other
333            52 : 48  2012           134          0         Europe
673            48 : 52  2013            72          1         Europe
717            54 : 46  2013           116          0          Other
1867           26 : 74  2016            65          1         Europe
728            58 : 42  2013           127          0         Europe

      research_lead
462            26.8
1854           22.6
1824           21.4
687            21.2
1830           20.5
333            20.0
673            19.6
717            18.9
1867           18.8
728            18.6
      total_score  rank_numeric
2276          NaN           401

In [232]:
# normalize into three relational tables
rankings = df[['university_name', 'year', 'rank_numeric', 'total_score', 'is_top100']].copy() 
scores= df[['university_name', 'year', 'teaching', 'research', 'citations', 'income', 'international']].copy()
institutions = df[['university_name', 'country', 'region', 'num_students', 'student_staff_ratio']].drop_duplicates(subset=['university_name']).copy()

conn = sqlite3.connect('rankings.db')

# load tables into SQLite
rankings.to_sql('rankings', conn, if_exists='replace', index=False)
scores.to_sql('scores', conn, if_exists='replace', index=False)
institutions.to_sql('institutions', conn, if_exists='replace', index=False)

def sql(query): return pd.read_sql_query(query, conn)

## Relational schema
* rankings: the primary keys are university_name, year
* scores: same primary keys
* institutions: the primary key is university_name

In [ ]:
# sql queries and pandas equivalence
# From the rankings table: select university_name, year, rank_numeric, total_score for the most recent year only,
#  where total_score is not null, ordered by total_score descending, limited to 10 rows.
sql("""
    select university_name, year, rank_numeric, total_score
    from rankings
    where year = (SELECT MAX(year) FROM rankings) and total_score is not null                    
    order by total_score DESC
    limit 10
    """)

#pandas equiv:
rankings[(rankings['year']== max(rankings['year'])) & (rankings['total_score'].notna())][['university_name', 'year', 'rank_numeric', 'total_score']].sort_values('total_score', ascending=False) [:10]


# Query 2 — average scores per country; JOIN to get country name; HAVING ≥3 universities
sql("""
    select i.country, avg(s.teaching), avg(s.research), avg(s.citations)
    From scores  s
    Join institutions i
    on s.university_name = i.university_name
    group by i.country
    having count(i.country) >=3
    order by avg(s.research) DESC
    """)

#pandas equiv
scores_insti_merge = pd.merge(scores,institutions, how = "left", on = 'university_name')
scores_insti = (scores_insti_merge.groupby('country').agg( average_teaching = ('teaching','mean'),
                                                         average_research = ('research', 'mean'),
                                                         average_citations = ('citations', 'mean'),
                                                         university_count = ('university_name', 'nunique')
                                                        ))

scores_insti = scores_insti[scores_insti['university_count'] >= 3]
scores_insti.sort_values('average_research', ascending = False)
scores_insti.head()

,average_teaching,average_research,average_citations,university_count
country,,,,
Australia,31.852137,36.118803,55.988889,31
Austria,30.535484,23.535484,57.180645,7
Belgium,35.629730,38.737838,61.062162,7
Brazil,36.308000,27.308000,19.028000,17
Canada,39.007407,42.267593,60.687963,25

In [299]:
# Query 3 — tier classification using CASE WHEN

sql("""
    select 
    case when rank_numeric between 1 and 50 then "Elite"
         when rank_numeric between 51 and 200 then "Top tier"
         when rank_numeric between 201 and 500 then "Strong"
         else "Other" end as tier,
        COUNT(*) AS row_count
    FROM rankings
    GROUP BY tier
    ORDER BY row_count DESC
    """)


# pandas equivalence:pd.cut is the equivalence of case when in sql
rankings['tier']= pd.cut(rankings['rank_numeric'], bins=[0,50,200,500,10000], labels=['Elite','Top tier','Strong','Other'])
print(rankings.groupby('tier').size())

tier
Elite        301
Top tier     900
Strong      1102
Other        300
dtype: int64

/var/folders/9k/ymj25sz10zd4511wlz920s4m0000hf/T/ipykernel_18217/4074805251.py:18: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  print(rankings.groupby('tier').size())

In [235]:
#Query 4 — rank within country via Window function
sql("""
    select r.university_name, i.country, r.rank_numeric, rank() over (partition by i.country order by r.rank_numeric) as "within-country rank"
    from rankings r
    join institutions i
    on r.university_name = i.university_name
    where  r.year = (SELECT max(year) FROM rankings)
    """)

# pandas equiv:
most_recent = rankings[rankings['year'] == rankings['year'].max()]
rank_insti_merge = pd.merge(most_recent, institutions, how="left", on="university_name")
rank_insti_merge['within_country_rank'] = rank_insti_merge.groupby('country')['rank_numeric'].rank(method='min').astype(int)
rank_insti_merge.head()

,university_name,year,rank_numeric,total_score,is_top100,tier,country,region,num_students,student_staff_ratio,within_country_rank
0,California Institute of Technology,2016,1,95.2,1,Elite,United States of America,North America,"2,243",6.9,1
1,University of Oxford,2016,2,94.2,1,Elite,United Kingdom,Europe,"19,919",11.6,1
2,Stanford University,2016,3,93.9,1,Elite,United States of America,North America,"15,596",7.8,2
3,University of Cambridge,2016,4,92.8,1,Elite,United Kingdom,Europe,"18,812",11.8,2
4,Massachusetts Institute of Technology,2016,5,92.0,1,Elite,United States of America,North America,"11,074",9.0,3

In [236]:
# Query 5 universities that improved rank year over year
sql(""" 
    select r_1.university_name, r_1.year, r_2.year, r_1.rank_numeric, r_2.rank_numeric, r_1.rank_numeric-r_2.rank_numeric as "improvement amount" 
    from rankings r_1
    join rankings r_2
    on r_1.university_name = r_2.university_name
    where r_2.year- r_1.year =1 
    order by "improvement amount" desc
    """)
#pandas equiv:
this_year = rankings.copy()
next_year = rankings.copy()
mrankings = this_year.merge(next_year, on ="university_name", suffixes=('_this_year', '_next_year'))
mrankings['improvement'] = mrankings['rank_numeric_this_year']- mrankings['rank_numeric_next_year']
mrankings[(mrankings['year_this_year']-mrankings['year_next_year'] == -1)][['university_name', 'year_this_year', 'year_next_year', 'rank_numeric_this_year', 'rank_numeric_next_year', 'improvement']].sort_values('improvement', ascending=False)

,university_name,year_this_year,year_next_year,rank_numeric_this_year,rank_numeric_next_year,improvement
9006,University of Erlangen-Nuremberg,2015,2016,276,123,153
9268,Aalborg University,2015,2016,351,201,150
9162,University of Cologne,2015,2016,301,156,145
8875,University of Münster,2015,2016,251,125,126
6516,Middle East Technical University,2014,2015,201,85,116
...,...,...,...,...,...,...
9200,University of Marrakech Cadi Ayyad,2015,2016,301,601,-300
8365,Istanbul Technical University,2015,2016,165,501,-336
8216,Boğaziçi University,2015,2016,139,501,-362
8547,Florida Institute of Technology,2015,2016,200,601,-401
7902,Middle East Technical University,2015,2016,85,501,-416

**Extension**: detecting multi-year improvement streaks would require either chaining 
additional self-joins or using a window function with `LAG()` — a natural next step 
for a more advanced version of this analysis.

## SQL–pandas equivalence check
* Results match across all five queries. 
* The main behavioral differences between these two methods are: 
- SQL sorts NULLs last by default while pandas sorts NaN first; 
- SQL JOIN produces no output for unmatched keys but pandas `merge` with `how='left'` preserves all left-side rows.

In [237]:
# Phase E: score matrix statistics 
# per-column summary statistics computed via numpy along axis=0
score_cols = ['teaching', 'research', 'citations', 'income', 'international']
df_clean = df[score_cols].dropna()
X= df_clean.values 

summary = pd.DataFrame({
    'mean': np.mean(X, axis=0),
    'std':  np.std(X, axis=0),
    'p25':  np.percentile(X, 25, axis=0),
    'p75':  np.percentile(X, 75, axis=0),
}, index=score_cols)
summary['IQR'] = summary['p75'] - summary['p25']
print(summary.round(2))

                mean    std    p25    p75    IQR
teaching       37.05  17.24  24.48  45.12  20.65
research       35.40  20.86  19.60  46.12  26.52
citations      60.39  23.01  45.10  78.30  33.20
income         48.97  21.16  33.10  59.00  25.90
international  52.82  22.15  34.30  70.10  35.80


## Score distribution
* `citations` has the highest mean and std, reflecting that a small number of research-intensive institutions score extremely high while most cluster lower.
* `international` has the largest IQR, meaning universities diverge most on this metric.

In [238]:
# center and normalize columns, then compute correlation matrix as Gram matrix

# Center X by subtracting the mean of each column. Shape stays (N, 5).
X_centered = X-X.mean(axis = 0)
X_centered.shape

# Normalize each column by dividing by its standard deviation. 
X_normed = X_centered/ X.std(axis=0)
N = X_normed.shape[0]

# Compute the correlation matrix as (X_normed.T @ X_normed) / N. Call it corr.
corr = (X_normed.T @ X_normed) /N
corr_df = pd.DataFrame(corr, index= score_cols, columns= score_cols)

# Verification: Compare to np.corrcoef(X.T). The maximum absolute difference should be essentially 0.
print((corr_df - pd.DataFrame(np.corrcoef(X.T), index=score_cols, columns=score_cols)).abs().max().max())

print(corr_df.round(3))

6.661338147750939e-16
               teaching  research  citations  income  international
teaching          1.000     0.915      0.489   0.329          0.148
research          0.915     1.000      0.513   0.382          0.257
citations         0.489     0.513      1.000   0.048          0.340
income            0.329     0.382      0.048   1.000          0.011
international     0.148     0.257      0.340   0.011          1.000

# Correlation structure
* `teaching` and `research` are the most correlated pair. Geometrically, this means these two column vectors are nearly parallel, so they 
contribute redundant information to the ranking.
* The correlation matrix here, as the Gram matrix of the mean-centered, column-normalized score vectors, is exactly the matrix PCA eigendecomposes. Its eigenvectors are the principal components; the fact that teaching and research are highly correlated means the first eigenvector loads heavily on both, and the effective dimensionality of the score space is lower than 5.